부산대 FE_이세형 6주차 과제 Step 1
kakao-tech-campus-2nd-step2/react-deploy pull request #17
Opened 2024-07-30 17:34 UTC by cla6shade

멘토님 안녕하세요~!

백엔드 개발자분들과 API 조정 후 구현할 스펙들을 모두 Mock API로 작동할 수 있게끔 변경했습니다.

백엔드 개발자들의 배포된 서버 URL을 선택할 수 있는 기능을 추가해서 .env 파일에 약간의 변동이 필요합니다.
저는 현재 로컬에서 아래와 같은 값을 입력 후 실행했습니다.

```
VITE_BASE_URL=https://react-gift-mock-api-git-main-cla6shades-projects.vercel.app
VITE_URLS=이세형=https://server.cla6sha.de,이세형1=https://server.abc.de
```

항상 시간 내어주셔서 감사합니다!

2024-07-31 22:28 UTC, MiaJLee requested changes
@cla6shade 세형님~ conflict 한번 봐주세요!

2024-08-01 05:04 UTC, cla6shade commented
안녕하세요 멘토님~
conflict 해결 완료했습니다!

감사합니다.

2024-08-01 13:36 UTC, MiaJLee requested changes
고생하셨습니다~ 세형님!
몇가지 리팩토링하면 좋을 포인트들 제안드렸어요! 확인 부탁드립니다~

2024-08-01 13:36 UTC, MiaJLee commented on src/components/organisms/semantic/header/APISelector.tsx
> +
urls와 apis를 초기화하는 별도 로직을 함수로 분리하면 좀 더 가독성이 높고, 유지보수에 편한 코드가 될 수 있을 것 같아요.
urls가 undefined 인 케이스도 고려하면 더 안전한 코드가 될 것 같습니다!

2024-08-01 13:36 UTC, MiaJLee commented on src/providers/LoginContextProvider.tsx
> +  const [isLoggedIn, setIsLoggedIn] = useState(typeof storedToken === 'string');
string 여부로 변경하신 이유가 있을까요??
코드에서는 storedToken 에 지정하는 문구가 정해져 있는 것 같은데, 정확한 문구와 비교해는 것은 어떨까요?

2024-08-01 13:36 UTC, MiaJLee commented on src/components/organisms/admin/AddCategoryForm.tsx
> +        </FormControl>
FormControl 부분, 에러메세지 노출하는 로직이 반복되고 있는데,
따로 해당 컴포넌트를 분리하면 중복을 많이 줄일 수 있을 것 같아요-!
에러문구 등 문자열도 상수로 분리하면 코드 가독성이나 유지보수에도 도움이 될 것 같습니다 :)

2024-08-01 13:36 UTC, MiaJLee commented on src/components/organisms/admin/AddProductForm.tsx
> +        </FormControl>
컴포넌트를 분리하면 여기서도 활용이 가능하겠네요!

2024-08-01 13:36 UTC, MiaJLee commented on src/hooks/useFetchProducts.ts
> +    console.log(url);
콘솔로그는 지워주세요-!

2024-08-01 19:21 UTC, cla6shade commented
멘토님 안녕하세요!

말씀해주신 내용을 모두 반영해봤지만, register 함수를 NameAdditionForm 에서 받는 중 타입 에러가 나서 어쩔 수 없이 any;타입으로 지정하게 되었습니다. 타입 assertion을 통해 해결하고자 했지만 그래도 에러가 나서.. 혹시나 어떻게 해결할 수 있을지 궁금합니다. 특히 any타입은 사용을 지양해야된다는 말을 어디서 줏어들어서, 조금 더 깔끔한 해결법이 있는지 궁금합니다.

감사합니다!

2024-08-02 01:11 UTC, MiaJLee commented on src/components/organisms/admin/NameAdditionForm.tsx
> +}
[공식문서](https://react-hook-form.com/ts#UseFormReturn) 찾아보니 
아래와 같이 작성하는 것 같은데, 혹시 해보셨을까요??

```suggestion
interface NameAdditionFormProps {
  additionType: 'product' | 'category';
  register: UseFormRegister<ProductFormInputData | CategoryFormInputData>;
  errors: FieldErrors<ProductFormInputData | CategoryFormInputData>;
}
```

2024-08-02 01:14 UTC, MiaJLee requested changes
세형님~ 추가 리뷰 확인 부탁드립니다~

2024-08-02 01:14 UTC, MiaJLee commented on src/components/organisms/admin/AddProductForm.tsx
> +        </FormControl>
아래의 FormControl까지 확장 가능한 컴포넌트가 아닌 상단의 컴포넌트만 병합하신 이유가 있는지 궁금해요~

2024-08-02 09:44 UTC, MiaJLee approved these changes
<img src="https://media4.giphy.com/media/EOpZ7XsVfTN2E/giphy.gif"/>
유용하게 사용할 수 있는 폼 컴포넌트를 만드신 것 같아요-!
고생하셨습니다 세형님 :) 👍

2024-08-02 09:44 UTC, merged

2024-08-03 08:29 UTC, cla6shade commented
역시 새벽에 코딩하면 안되겠어요..
다시한 번 잘 생각해볼 수 있는 기회가 되었습니다. 감사합니다!