부산대 FE_한재안 6주차 과제 Step1
kakao-tech-campus-2nd-step2/react-deploy pull request #31
Opened 2024-08-01 07:32 UTC by JaeanHan

안녕하세요 멘토님!
생각보다 쉽지 않은 것 같습니다 ㅠㅠ!
백엔드는 http로 배포가 이미 된 상태라, 로컬에서 요청이 가능해 요청, 응답 형식은 확인해 잘 작동하는 거 확인했습니다.
추가적으로 제가 백엔드 서버 주소를 깃허브에 올려버려서, 이거에 대해서 백엔드 분들에게 사과드리고 협의를 하는 과정에 시간이 조금 걸렸습니다.

감사합니다!

2024-08-01 13:57 UTC, wacilpong commented
@JaeanHan 
안녕하세요 재안님~
해당 피알에 스텝0, 1이 섞여서 파일체인지가 너무 많아 중점적으로 봐야할 부분이 헷갈려서 그런데, 스텝0를 따로 올려주시거나 어느 커밋부터 봐야하는지 알려주시겠어요? 대충 보기로는 5fa5167 부터 보면 될까요?

2024-08-01 15:02 UTC, JaeanHan commented
> @wacilpong  대충 보기로는 [5fa5167](https://github.com/kakao-tech-campus-2nd-step2/react-deploy/commit/5fa516745ba286a3d850e14ff8641c5c3e083dd9) 부터 보면 될까요?

헉... 네 언급해주신 부분이 맞습니다 ㅠㅠㅠ 커밋 메세지를 통해 말씀드리려고 했는데 죄송합니다..😭😭

2024-08-01 15:39 UTC, wacilpong requested changes
이번 피알은 스텝0,1이 합쳐져 파일체인지가 큰 관계로 커밋단위로 코멘트를 달아두었습니다~ 확인 부탁드리고, 마지막 주차까지 힘내봅시다~

2024-08-01 15:39 UTC, wacilpong commented on src/api/types.ts
> +};
이건 서버쪽과 협의된 인터페이스같은데요, 혹시 number필드는 무슨값인가요? 필드명이 좀 모호한데, 심지어 number타입 키워드와 같은 이름이기도 하고요. 만약 서버에서 정한 이름이라고 하더라도, 재안님도 뜻을 아우를 수 없는 이름이라고 생각되면 서버에 요청해서 바꿔보면 어떨까요? 참고로 현업에서도 서버쪽 인터페이스가 FE와 어우러질 수 없다고 판단하면 꼭 말해서 협의하는 일이 굉장히 많습니다.

2024-08-01 15:39 UTC, wacilpong commented on src/api/hooks/useGetProducts.ts
> +  return `${fetchInstance.defaults.baseURL}/api/products/categories/${categoryId}?page=${pageToken ? pageToken : 0}&${maxResults ? `size=${maxResults}&` : ''}sort=price,asc`;
저는 개인적으로 이전 new URLSearchParams()를 쓴 형태가 훨씬 쉽게 읽힌다고 생각하는데요. 이렇게 바꾼 이유가 있으실까요? 저는 개인적으로 단지 몇줄 줄이는 것보다 남들이 봤을때 더 알아보기 쉬운 형태를 선호해서 말씀드려봅니다.

```
const params = new URLSearchParams();

params.append('page', pageToken || 0);
params.append('sort', 'price,asc');

if (maxResults) params.append('size', maxResults);

return `${baseURL}/api/products/categories/${categoryId}?${params.toString()}`;
``

2024-08-01 15:39 UTC, wacilpong commented on src/components/features/Layout/Header.tsx
> +    console.log(fetchInstance.defaults.baseURL);
의도한 콘솔로그라면 주석을 달아주시고, 아니라면 콘솔로그는 지우고 피알을 올리는 것이 좋습니다.

2024-08-01 15:39 UTC, wacilpong commented on src/api/utils.ts
> +    const { token } = response.data.data;
서버 공통응답으로 response.data.data 형태로 오는 것 같은데요, method(GET/POST/PUT...)상관없이 모든 응답이 이 인터페이스를 따르는게 맞다면, 응답 인터셉터에서 공통으로 빼오면 좋을 것 같아요.

```
fetchInstance.interceptors.response.use(
  response => {
    if (response.data && response.data.data) {
      return response.data.data;
    }

    return response;
  },
  error => {
    return Promise.reject(error);
  }
);

```

2024-08-02 06:24 UTC, JaeanHan commented on src/api/types.ts
> +};
우선, number 필드는 currentPageNumber를 의미한다고 합니다! 해당 필드는 서버 쪽에서 정한 객체인데요. 이번에 변경을 요청 해봤습니다. 그런데 서버 쪽에선 주어진 객체를 사용하는 상황이라 해당 객체를 변경 할 수 없다고 합니다 ㅠㅠ! 

추가적으로 해당 객체는 사용하지 않는 객체입니다..! 처음 탬플릿 코드가 해당 객체를 사용해 서버가 주는 모든 값들을 우선적으로 받은 후, 필요한 값들만 필터링해서 다른 객체에 옮긴 후 사용하는 형식이었는데요.
형식을 따라가야하나? 생각했던 참에 그냥 없애버렸습니다..!

>  현업에서도 서버쪽 인터페이스가 FE와 어우러질 수 없다고 판단하면 꼭 말해서 협의하는 일이 굉장히 많습니다.

다음 API 명세서를 작성할 때, 참고해서 서버쪽에도 요청하겠습니다!

2024-08-02 06:28 UTC, JaeanHan commented on src/api/hooks/useGetProducts.ts
> +  return `${fetchInstance.defaults.baseURL}/api/products/categories/${categoryId}?page=${pageToken ? pageToken : 0}&${maxResults ? `size=${maxResults}&` : ''}sort=price,asc`;
해당 부분은, 먼가 백엔드와 api를 붙일 때, 다 맞는데 왜 안되지..? 요청 url에서 `,`가 변환돼서 그런가? 원래 변환돼서 가는거 아닌가..? 혹시 바꿔볼 까..? 라고 생각하며 다 바꾸던 도중, 코드를 바꾸니까 백엔드와 붙었어서 그대로 남겨뒀었습니다..! 
그런데 해당 리뷰를 확인 후 이전 코드로 되돌려서 실행해 보니까 잘 되는 것 같습니다..! 코드가 아닌 세팅 쪽 문제였는데 시기가 잘 맞아 떨어져 코드 문제라고 생각했었습니다..!

2024-08-02 06:39 UTC, JaeanHan commented on src/components/features/Layout/Header.tsx
> +    console.log(fetchInstance.defaults.baseURL);
해당 콘솔로그는 피알 올리기 전에 삭제했습니다..! 코드 변경점이 너무 많아 변경점들이 확실히 보이지 않은 것 같습니다.. 죄송합니다.. ㅠㅠ! 현재 Step2(배포 및 CI/CD)를 진행 중인데, 앞으로 CI/CD를 생각하며 변경점들을 올리겠습니다!

2024-08-02 06:45 UTC, JaeanHan commented on src/api/utils.ts
> +    const { token } = response.data.data;
아 제가 일일이 하나씩 다 수정했는데 인터셉터를 사용하면 더 편하게 할 수 있었네요..! 
감사합니다 위와 같은 방법으로 수정하겠습니다!

2024-08-02 16:29 UTC, wacilpong approved these changes
리뷰 반영해주신 것 모두 확인했습니다!! 깃헙페이지로 배포하셨군요. 이런 배포서비스를 static site hosting 서비스라고 부르는데요. 리액트같은 SPA는 클라이언트 사이드만 필요하기 때문에 이런 정적호스팅 서비스로 간단하게 배포할 수 있고, 이런것부터 시작해서 빌드-배포 파이프라인을 먼저 이해해도 좋습니다.

이를 제대로 이해한 다음에 저번에 말씀하셨던 도커 컨테이너 기반 배포를 진행해보시면 좋겠네요~

해당 피알은 이만 머지해보겠습니다. 수고 많으셨어요

2024-08-02 16:29 UTC, merged