전남대 FE_정서윤 6주차 과제 Step1
kakao-tech-campus-2nd-step2/react-deploy pull request #41
Opened 2024-08-01 17:07 UTC by yunn23

안녕하세요 멘토님! 6주차 step1 과제 구현중 문제 해결이 되지 않아 질문 드립니다.

백엔드측이 계속 개발중이라 msw로 구현하게 되었습니다. 로그인 및 회원가입과 위시리스트 부분부터 msw 코드를 작성하였는데, 두 부분 모두 네트워크 에러가 계속해서 발생하고 있습니다.. 혹시 어떤 오류인지 알 수 있을까요? 엔드포인트를 맞춰 잘 작성한 것 같은데 오류가 지속되는 원인이 무엇일까요?

(로그인은 주문창이 넘어가져야하기 때문에 아직 임시로그인 코드를 살려뒀습니다.)

과제 구현을 하다보면 부족한 부분이 많다고 느낍니다 항상 문제 해결에 도움 주셔서 감사합니다

2024-08-03 02:05 UTC, taehwanno requested changes
피드백드려요!

2024-08-03 02:05 UTC, taehwanno commented on src/api/hooks/members.mock.ts
> +    const { email, password } = req.body as { email: string, password: string };
req.body는 msw에서 deprecated 되어서 `await req.json()`을 써주시는게 좋겠습니다. 또한 `as`를 통해 type assertion으로 요청 바디의 타입을 표현해주고 있는데 그것보다는 msw에서 권장하는 방법이 있으니 [공식문서](https://mswjs.io/docs/best-practices/typescript/#http-handlers) 참고하셔서 한번 개선해보면 좋겠습니다.

2024-08-03 02:05 UTC, taehwanno commented on src/api/instance/index.ts
> +let axiosInstanceWithToken: AxiosInstance;
API 통신할 때 axios instance를 여러 개로 나누지 않고 하나로 일관되게 구성해서 사용하는게 더 편리할텐데 어떤 이유로 분리하게 됐나요?
토큰 여부에 따라 달라지는건 56번~57번 라인처럼 토큰이 있다면 전달하고 없다면 전달하지 않도록 구성하면 될 거 같아서요!

2024-08-03 02:05 UTC, taehwanno commented on src/api/hooks/useGetProducts.ts
> +  const response = await fetchInstance().get<ProductsResponseRawData>(getProductsPath(params));
호출하는 API의 도메인이 1개로 보여서 instance를 직접 불러오는 것보다는 axios default instance를 통해 요청되도록 하는게 더 간단해보여요.

```tsx
import axios from 'axios';

const response = await axios.get<ProductsResponseRawData>(getProductsPath(params));
```

2024-08-03 02:05 UTC, taehwanno commented on src/api/instance/index.ts
> +  axiosInstanceWithToken.defaults.baseURL = BASE_URL;
> 헤더에서 백엔드 baseurl을 선택할 수 있는 컴포넌트를 구현했지만, 제대로 baseurl이 바뀌고 있는지 잘 모르겠습니다. 콘솔에 찍히는 baseurl을 변경되고 있지만, 컴포넌트들이 바뀌지 않는 것 같습니다.

Chrome DevTools의 Network 탭에서 HTTP 요청의 주소를 살펴볼 수 있습니다. 아래 링크 참고하셔서 활용해보시겠어요? 제가 테스트 해봤을 때는 base url 변경이 확인되고 있어요.

- [리소스 세부정보 검사 - 네트워크 활동 검사](https://developer.chrome.com/docs/devtools/network?hl=ko#details)

2024-08-03 02:05 UTC, taehwanno commented on src/api/instance/index.ts
> +  axiosInstance.defaults.baseURL = BASE_URL;
참고로 axios는 config 설정시 우선순위가 있다는 점도 인식하고 있으시면 좋겠습니다. 전역 기본값, 커스텀 인스턴스 기본값, 커스텀 인스턴스를 통한 호출 3가지가 가능한데 후자로 갈수록 우선순위가 높습니다.

- [Config 기본값](https://axios-http.com/kr/docs/config_defaults)

2024-08-03 02:05 UTC, taehwanno commented on src/components/features/Home/ApiSelection/index.tsx
> +        <option value="">
초기 로딩시 빈 값으로 주기보다는 currentBaseURL를 통해 매칭되는 API 이름으로 설정되도록 하는게 좋겠습니다.

2024-08-03 02:05 UTC, taehwanno commented on src/api/hooks/wishlist.mock.ts
> +    console.log('요청 헤더:', _req.headers.get('Content-Type')); // 디버깅 로그 추가
mock handler에서 console.log로 찍고 있는 대부분의 값은 Chrome DevTools Network 탭에서 확인 가능하니 제거하고, 개발자 도구를 한번 학습해보시는게 좋겠습니다.

2024-08-03 04:48 UTC, yunn23 commented on src/api/instance/index.ts
> +let axiosInstanceWithToken: AxiosInstance;
오 토큰 여부 때문에 분리했었는데 위 방법으로 axios instance 통일하였습니다!

2024-08-04 01:57 UTC, taehwanno approved these changes
고생하셨습니다.

2024-08-04 01:57 UTC, merged