부산대 FE_차기은 6주차 과제 제출 Step1
kakao-tech-campus-2nd-step2/react-deploy pull request #43
Opened 2024-08-01 19:14 UTC by harugi7

일단 category 부분 나오도록 수정해서 pr 날립니다... 이번주도 잘 부탁드립니다...

2024-08-01 20:09 UTC, harugi7 commented
https://react-deploy-2hf.pages.dev/

2024-08-02 01:16 UTC, MiaJLee requested changes
기은님~ 이전 코드 이전하는 내용만 따로 떼어서 step0으로 올려주심 리뷰에 도움이 될 것 같습니다~

2024-08-02 07:00 UTC, MiaJLee requested changes
head 브랜치 한번 당겨주시면서 컨플릭트 봐주세요~!

2024-08-02 09:51 UTC, MiaJLee approved these changes
기은님 고생하셨습니다~
마이너한 이슈지만 한번 봐주세요!

2024-08-02 09:51 UTC, MiaJLee commented on src/index.tsx
> +// });
사용하지 않는 코드는 제거해주세요 :)

2024-08-02 09:51 UTC, MiaJLee commented on src/pages/MyAccount/index.tsx
> +      {authInfo?.id ? (
삼항연산자는 두번 이상 nested 되면 코드 가독성이 떨어질 수 있어요~
이같은 경우에는 ‘로그인 정보를 찾을 수 없습니다’ 를 if 문으로 early return 시키는게 더 나아보여요!

2024-08-02 09:52 UTC, MiaJLee requested changes
> 기은님 고생하셨습니다~
> 마이너한 이슈지만 한번 봐주세요!

실수로 approve를 해버렸네요~ 확인 부탁해요

2024-08-02 16:40 UTC, harugi7 commented on src/pages/MyAccount/index.tsx
> +      {authInfo?.id ? (
네 감사합니다!

2024-08-02 16:40 UTC, harugi7 commented
네 확인하였습니다! 마지막 주도 감사합니다!! 수고하셨습니🥰

2024-08-03 23:27 UTC, MiaJLee approved these changes
6주간 고생하셨습니다 기은님-!
바로 머지 할게요!

2024-08-03 23:27 UTC, merged