Step1
kakao-tech-campus-2nd-step2/react-deploy pull request #45
Opened 2024-08-01 20:10 UTC by dlwltn0430

2024-08-02 01:16 UTC, MiaJLee requested changes
지수님~ 이전 코드 이전하는 내용만 떼어서 step0 pr 부탁드려요~

2024-08-03 23:28 UTC, MiaJLee requested changes
Head 브랜치 한번 당겨주세요~!

2024-08-04 22:29 UTC, MiaJLee requested changes
지수님~ 브랜치 당겨오면서 컨플릭트 문구가 남아있어서요-!
확인 한번 해주세요!

2024-08-04 22:29 UTC, MiaJLee commented on .gitignore
> +>>>>>>> upstream/dlwltn0430
여기 머지하면서 같이 들어온 것 같아요~

2024-08-04 22:29 UTC, MiaJLee commented on package.json
> +>>>>>>> upstream/dlwltn0430
여기두요!

2024-08-04 22:29 UTC, MiaJLee commented on public/index.html
> +=======
전체적으로 한번 확인해주셔야 할 것 같네요 ㅎㅎ

2024-08-05 03:15 UTC, dlwltn0430 commented
> 지수님~ 브랜치 당겨오면서 컨플릭트 문구가 남아있어서요-! 확인 한번 해주세요!

vscode에서 파일이 빨간색으로 안 떠서 컨플릭트가 아직 있는지 몰랐네요ㅠ 수정 후 다시 리뷰 요청 드릴게요!

2024-08-05 12:35 UTC, MiaJLee approved these changes
지수님~ 6주라는 짧은 시간에도 높은 퀄리티의 작업을 만들어주셨네요!
지수님의 사려깊은 코드 덕분에 코드가 정말 잘 읽혔어요.
그간 정말 고생하셨습니다 :) 남은 방학, 남은 프로그램도 마무리 잘 하시길 바랍니다 ! 👍

2024-08-05 12:35 UTC, MiaJLee commented on src/pages/MyAccount/index.tsx
> +                {/* {item.price}원 */}
주석은 제거해주세요-!

2024-08-05 12:36 UTC, merged

2024-08-05 14:02 UTC, dlwltn0430 commented
> 지수님~ 6주라는 짧은 시간에도 높은 퀄리티의 작업을 만들어주셨네요! 지수님의 사려깊은 코드 덕분에 코드가 정말 잘 읽혔어요. 그간 정말 고생하셨습니다 :) 남은 방학, 남은 프로그램도 마무리 잘 하시길 바랍니다 ! 👍

멘토님도 6주 동안 고생 많으셨습니다! 😄