부산대 FE 이민경 6주차 과제 Step1, 2
kakao-tech-campus-2nd-step2/react-deploy pull request #61
Opened 2024-08-02 08:20 UTC by mingkyeongg

초반에 시행착오가 많아 커밋이 조잡합니다ㅜㅜ
백엔드 API의 서버가 꺼지면 실행이 안될 수도 있는 점 양해부탁드립니다🥲

1. 카테고리, 상품 API 연결
2. github pages 배포

카카오 로그인은 인가 코드를 어디서 처리해야하는지 소통중입니다
카카오 로그인이 되어야 주문하기, 나의 페이지 확인이 가능해 그 부분은 아직 테스트하지 못했습니다.

https://mingkyeongg.github.io/react-deploy/
배포 주소입니다!

2024-08-04 02:17 UTC, JunilHwang requested changes
안녕하세요 민경님~
일단 NextStep platform 에서 리뷰 요청을 보내주세요 ㅠㅠ
그리고 정상적으로 동작하지 않는 부분들이 많은 것 같아요.
한 번 같이 확인 부탁드립니다!

2024-08-04 02:17 UTC, JunilHwang commented on src/api/instance/index.ts
> +export const BASE_URL = 'http://54.180.245.166:8080';
현재 API를 불러올 수 없는 상태네요 ㅠㅠ

<img width="1190" alt="image" src="https://github.com/user-attachments/assets/5065b6e5-0df7-45e9-b2a8-07b774b57e7e">

일이렇게 cors 에러가 발생하는 것 같아요.

2024-08-04 02:17 UTC, JunilHwang commented on package.json
> +  "homepage": "https://mingkyeongg.github.io/react-deploy/",
배포는 잘 해주셨네요!

2024-08-04 02:17 UTC, JunilHwang commented on src/pages/Login/index.tsx
> +  const authorizeUrl = 'api/oauth/authorize';
`https://mingkyeongg.github.io/react-deploy/api/oauth/authorize`

이 페이지로 접근할 수 없어서, 카카오톡 로그인을 해도 정상적으로 진행이 안 되는 상황입니다.
이를 어떻게 해결할 수 있을까요?

힌트는 hash router 입니다!

2024-08-05 04:43 UTC, mingkyeongg commented on src/api/instance/index.ts
> +export const BASE_URL = 'http://54.180.245.166:8080';
현재 백엔드 서버가 꺼졌다가 켜지면 주소가 바뀌어서ㅜㅜ 변경된 것 같습니다....!!

2024-08-05 07:20 UTC, mingkyeongg commented on src/pages/Login/index.tsx
> +  const authorizeUrl = 'api/oauth/authorize';
http와 https의 충돌이 일어나는데 이는 어떻게 해결하면 좋을까요...?!
아니면 이 문제와는 다른 내용일까요...?!

2024-08-06 03:08 UTC, JunilHwang requested changes

2024-08-06 03:08 UTC, JunilHwang commented on src/pages/Login/index.tsx
> +  const authorizeUrl = 'api/oauth/authorize';
이건 카카오톡 로그인을 시도할 때 redirect를 하는 부분이 있는데,
redirect 주소에 아예 접근을 못해서 발생하는 문제입니다.
말씀해주신것과는 연관이 없답니다!

2024-08-06 03:08 UTC, JunilHwang commented on src/api/instance/index.ts
> +export const BASE_URL = 'http://54.180.245.166:8080';
그럼 이런 문제는 어떻게 해결할 수 있을까요!?

2024-08-06 08:55 UTC, JunilHwang approved these changes
Step4 PR이 올라와서, 이 PR은 머지하도록 하겠습니다!

2024-08-06 08:55 UTC, merged