부산대 FE_이경서 6주차 과제 step1,2
kakao-tech-campus-2nd-step2/react-deploy pull request #77
Opened 2024-08-02 13:01 UTC by rudtj

안녕하세요 멘토님!
부득이하게 step1,2단계를 함께 제출하게 되었습니다ㅠㅠ
아직 머지를 안해주셔서 일단 pr부터 날리겠습니다!
githubpages로 배포를 했는데 정적 배포라 이렇게만 해도 되는지 피드백 주시면 받아서 해결하겠습니다!!

2024-08-04 01:49 UTC, JunilHwang requested changes
@rudtj 
안녕하세요 경서님!
일단 nextstep 에서 리뷰 요청을 보내주셔야할 것 같아요..!

2024-08-04 02:08 UTC, JunilHwang requested changes
안녕하세요 경서님~
배포는 정상적으로 된 것 같은데
배포만... 정상이네요 ㅎㅎ;

어플리케이션에 지금 문제가 많아보여요 ㅠㅠ
그리고 PR에 conflict가 있는 것 같아서 이 부분도 같이 확인 부탁드립니다!

2024-08-04 02:08 UTC, JunilHwang commented on package.json
> +  },
경서님! 일단 어떤 링크로 배포되었는지 PR 본문에 명시해주시면 좋았을 것 같아요 ㅠㅠ
이런식으로 제가 직접 찾아야하네요 ㅎㅎ;

2024-08-04 02:08 UTC, JunilHwang commented on src/routes/index.tsx
> +    path: RouterPath.root,
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/4463aadf-1b52-4f1d-9118-af9370c4a992">

배포된 페이지로 이동하면 다시 페이지의 루트로 이동이 되고,
그 상태에서 새로고침을 하면 페이지가 없기 때문에 404 not found가 발생한답니다!

https://github.com/user-attachments/assets/dd50267f-be6f-4873-b978-3f7f03821e5d

2024-08-04 02:08 UTC, JunilHwang commented on src/api/instance/index.ts
> +});
API 주소 변경이 필요할 것 같아요..!
데이터를 불러올 수가 없네요 ㅎㅎ;

2024-08-06 05:51 UTC, JunilHwang approved these changes
안녕하세요 경서님!
아직 라우터 관련 문제는 해결되지 않았네요 ㅎㅎ
API는 정상동작 확인했습니다.
일단 Approve 하겠습니다.

2024-08-06 05:51 UTC, merged

2024-08-06 13:41 UTC, rudtj commented
@JunilHwang 멘토님 제가 step3,4를 pr 날렸는데 충돌이 너무 많아서 해결이 안됩니다..이건 어떻게 해결할 수 있을까요?ㅠㅠ