부산대 FE_이경서 6주차 과제 step0
kakao-tech-campus-2nd-step2/react-deploy pull request #8
Opened 2024-07-30 09:24 UTC by rudtj

안녕하세요 멘토님!
벌써 마지막 주라니 시간이 정말 호로록 지나간 것 같아요..!
이전 과제 불러와서 step0 완료했습니다.
마지막 과제까지 최선을 다해 진행하겠습니다!!

2024-08-01 09:08 UTC, JunilHwang commented
@rudtj 
안녕하세요 경서님..!
아마 node_modules 가 git에 포함되서 그런 것 같아요.
node_modules 폴더를 gitignore에 추가해주고 다시 요청주실 수 있을까요?

2024-08-01 09:08 UTC, JunilHwang requested changes
@rudtj 
안녕하세요 경서님..!
아마 node_modules 가 git에 포함되서 그런 것 같아요.
node_modules 폴더를 gitignore에 추가해주고 다시 요청주실 수 있을까요?

2024-08-01 14:14 UTC, rudtj commented
멘토님 제가 gitignore를 추가했는데 여전히 파일 변경과 커밋 내역이 너무 많습니다..여기서 더 진행을 해도 되는걸까요?

2024-08-02 03:01 UTC, JunilHwang commented
@rudtj 
캐시를 날려야 한답니다!
이렇게 한 번 진행해주세요~

```bash
$ git rm -r --cached .
$ git add .
$ git commit -m "chore: node_modules 제거"
```

2024-08-02 03:01 UTC, JunilHwang requested changes
@rudtj 
캐시를 날려야 한답니다!
이렇게 한 번 진행해주세요~

```bash
$ git rm -r --cached .
$ git add .
$ git commit -m "chore: node_modules 제거"
```

2024-08-02 06:28 UTC, rudtj commented
@JunilHwang 수정했습니다! 머지해주시면 바로 다음 단계 올리겠습니다!!

2024-08-02 16:35 UTC, JunilHwang approved these changes
확인 완료했습니다 경서님~ 바로 머지하겠습니다!

2024-08-02 16:35 UTC, merged